#!/usr/bin/env bash

set -e

# Utility to work on remote host

DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [[ -z ${HST} || -z ${USR} || -z ${DST} ]];
then
        echo -e "\e[1;31mHost variables \$HST, \$USR, \$DST must be set\e[0m" >&2
        echo -e \$TGT can also be set for cross compilation
        echo -e You can also set override per service e.g. \$wattflux_HST, \$linky_TGT
        exit 1
fi

# open remote shell
open_shell() {
        local service_HST="${service}_HST"
        _HST=${!service_HST:-$HST}
        local service_DST="${service}_DST"
        _DST=${!service_DST:-$DST}

        echo -e "\e[1;32mOpening shell\e[0m"
        ssh ${_HST} -t "cd ${_DST} ; bash --login"
}

clean_service() {
        if [[ -z ${service} ]];
        then
                echo -e "\e[1;31mService must be specified as first argument\e[0m" >&2
                exit 1
        fi

        echo -e "Cleaning service \e[1;32m${service}\e[0m"
        cargo clean --package ${service}
        rm -rf ${service}/dist
}

compile_service() {
        if [[ -z ${service} ]];
        then
                echo -e "\e[1;31mService must be specified as first argument\e[0m" >&2
                exit 1
        fi

        local service_TGT="${service}_TGT"
        _TGT=${!service_TGT:-$TGT}

        if [[ -z ${_TGT} ]];
        then
                echo -e "Compiling service \e[1;32m${service}\e[0m"
                cargo build --release --package ${service}
        else
                echo -e "Cross compiling service \e[1;32m${service}\e[0m for target \e[1;32m${_TGT}\e[0m"
                cargo cross build --target ${_TGT} --release --package ${service}
        fi
}

dist_service() {
        if [[ -z ${service} ]];
        then
                echo -e "\e[1;31mService must be specified as first argument\e[0m" >&2
                exit 1
        fi

        local service_HST="${service}_HST"
        _HST=${!service_HST:-$HST}
        local service_DST="${service}_DST"
        _DST=${!service_DST:-$DST}
        local service_TGT="${service}_TGT"
        _TGT=${!service_TGT:-$TGT}

        if [[ -z ${_TGT} ]];
        then
                bin_path=target/release/${service}
        else
                bin_path=target/${_TGT}/release/${service}
        fi

        if [[ ! -f ${bin_path} ]];
        then
                echo -e "\e[1;31mBinary not found at ${bin_path}, please compile the service first\e[0m" >&2
                exit 1
        fi

        mkdir -p ${service}/dist
        cp -u ${bin_path} ${service}/dist/

        if [[ -f ${service}/${service}.service ]];
        then
                cp -u ${service}/${service}.service ${service}/dist/
        fi
        if [[ -f ${service}/${service}.yml ]];
        then
                cp -u ${service}/${service}.yml ${service}/dist/
        fi

        # upload to remote
        rsync -va  ${service}/dist/ ${_HST}:${_DST}
}

install_service() {
        if [[ -z ${service} ]];
        then
                echo -e "\e[1;31mService must be specified as first argument\e[0m" >&2
                exit 1
        fi

        echo -e "Installing \e[1;32m${service}\e[0m service"

        local service_HST="${service}_HST"
        _HST=${!service_HST:-$HST}
        local service_DST="${service}_DST"
        _DST=${!service_DST:-$DST}
        local service_TGT="${service}_TGT"
        _TGT=${!service_TGT:-$TGT}

        ssh ${_HST} 'bash -s' <<EOF
                cd ${_DST}
                if [[ ! -f ${service}.service || ! -f ${service} ]];
                then
                        echo -e "\e[1;31mService files not found in ${_DST}, please upload the service first\e[0m" >&2
                        exit 1
                fi

                sudo install ${service} /usr/local/bin/${service}
                sudo install ${service}.service /etc/systemd/system/${service}.service
                if [[ -f ${service}.yml ]];
                then
                        sudo install ${service}.yml /etc/${service}.yml
                fi
                sudo systemctl daemon-reload
EOF
}

start_service() {
        if [[ -z ${service} ]];
        then
                echo -e "\e[1;31mService must be specified as first argument\e[0m" >&2
                exit 1
        fi

        echo -e "Starting \e[1;32m${service}\e[0m service"

        local service_HST="${service}_HST"
        _HST=${!service_HST:-$HST}
        local service_DST="${service}_DST"
        _DST=${!service_DST:-$DST}
        local service_TGT="${service}_TGT"
        _TGT=${!service_TGT:-$TGT}

        ssh ${_HST} 'bash -s' <<EOF
                cd ${_DST}
                if [[ ! -f ${service}.service || ! -f ${service} ]];
                then
                        echo -e "\e[1;31mService files not found in ${_DST}, please upload the service first\e[0m" >&2
                        exit 1
                fi

                sudo systemctl start ${service}
                sudo systemctl enable ${service}
EOF
}

stop_service() {
        if [[ -z ${service} ]];
        then
                echo -e "\e[1;31mService must be specified as first argument\e[0m" >&2
                exit 1
        fi

        echo -e "Stopping \e[1;32m${service}\e[0m service"

        local service_HST="${service}_HST"
        _HST=${!service_HST:-$HST}
        local service_DST="${service}_DST"
        _DST=${!service_DST:-$DST}
        local service_TGT="${service}_TGT"
        _TGT=${!service_TGT:-$TGT}

        ssh ${_HST} 'bash -s' <<EOF
                cd ${_DST}
                if [[ ! -f ${service}.service || ! -f ${service} ]];
                then
                        echo -e "\e[1;31mService files not found in ${_DST}, please upload the service first\e[0m" >&2
                        exit 1
                fi

                sudo systemctl stop ${service}
                sudo systemctl disable ${service}
EOF
}

restart_service() {
        if [[ -z ${service} ]];
        then
                echo -e "\e[1;31mService must be specified as first argument\e[0m" >&2
                exit 1
        fi

        echo -e "Restarting \e[1;32m${service}\e[0m service"

        local service_HST="${service}_HST"
        _HST=${!service_HST:-$HST}
        local service_DST="${service}_DST"
        _DST=${!service_DST:-$DST}
        local service_TGT="${service}_TGT"
        _TGT=${!service_TGT:-$TGT}

        ssh ${_HST} 'bash -s' <<EOF
                cd ${_DST}
                if [[ ! -f ${service}.service || ! -f ${service} ]];
                then
                        echo -e "\e[1;31mService files not found in ${_DST}, please upload the service first\e[0m" >&2
                        exit 1
                fi

                sudo systemctl restart ${service}
EOF
}

service_status() {
        if [[ -z ${service} ]];
        then
                echo -e "\e[1;31mService must be specified as first argument\e[0m" >&2
                exit 1
        fi

        echo -e "Sleeping for 1 second to let journal catch up with service status changes"
        sleep 1

        echo -e "Checking status of \e[1;32m${service}\e[0m service"

        local service_HST="${service}_HST"
        _HST=${!service_HST:-$HST}
        local service_DST="${service}_DST"
        _DST=${!service_DST:-$DST}
        local service_TGT="${service}_TGT"
        _TGT=${!service_TGT:-$TGT}

        ssh ${_HST} 'bash -s' <<EOF
                cd ${_DST}
                if [[ ! -f ${service}.service || ! -f ${service} ]];
                then
                        echo -e "\e[1;31mService files not found in ${_DST}, please upload the service first\e[0m" >&2
                        exit 1
                fi

                sudo systemctl status ${service}
EOF
}

export service=

while [ $# -gt 0 ]
do
        case "$1" in
                linky)
                        service=linky
                        ;;
                wattflux)
                        service=wattflux
                        ;;
                ssh)
                        open_shell
                        ;;
                clean)
                        clean_service
                        ;;
                compile)
                        compile_service
                        ;;
                dist)
                        dist_service
                        ;;
                install)
                        install_service
                        ;;
                start)
                        start_service
                        ;;
                stop)
                        stop_service
                        ;;
                restart)
                        restart_service
                        ;;
                status)
                        service_status
                        ;;
                *)
                        echo -e "\e[1;31mUnknown command or service: $1\e[0m" >&2
                        echo "Usage: remote [command]" >&2
                        echo "Available commands: ssh, compile, dist, clean" >&2
                        exit 1
                        ;;
        esac
        shift
done
