#!/usr/bin/env bash

set -e

# Utility to work on remote host

DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [[ -z ${HST} || -z ${USR} || -z ${DST} ]];
then
        echo -e "\e[1;31mHost variables \$HST, \$USR, \$DST must be set\e[0m" >&2
        echo -e \$TGT can also be set for cross compilation
        echo -e You can also set override per service e.g. \$wattflux_HST, \$linky_TGT
        exit 1
fi

get_service_config() {
        local service_HST="${service//-/_}_HST"
        _HST=${!service_HST:-$HST}
        local service_DST="${service//-/_}_DST"
        _DST=${!service_DST:-$DST}
        local service_TGT="${service//-/_}_TGT"
        _TGT=${!service_TGT:-$TGT}
}

# open remote shell
open_shell() {
        get_service_config

        echo -e "\e[1;32mOpening shell\e[0m"
        ssh ${_HST} -t "cd ${_DST} ; bash --login"
}

service_clean() {
        if [[ -z ${service} ]];
        then
                echo -e "\e[1;31mService must be specified as first argument\e[0m" >&2
                exit 1
        fi

        echo -e "Cleaning service \e[1;32m${service}\e[0m"
        cargo clean --package ${service}
        rm -rf ${service}/dist
}

service_compile() {
        if [[ -z ${service} ]];
        then
                echo -e "\e[1;31mService must be specified as first argument\e[0m" >&2
                exit 1
        fi

        get_service_config

        if [[ -z ${_TGT} ]];
        then
                echo -e "Compiling service \e[1;32m${service}\e[0m"
                cargo build --release --package ${service}
        else
                echo -e "Cross compiling service \e[1;32m${service}\e[0m for target \e[1;32m${_TGT}\e[0m"
                cargo cross build --target ${_TGT} --release --package ${service}
        fi

        if [[ ${service} == "domotux" ]];
        then
                echo -e "Compiling frontend assets for \e[1;32mdomotux\e[0m"
                pushd ${DIR}/facade > /dev/null
                pnpm build
                popd > /dev/null
        fi
}

service_dist() {
        if [[ -z ${service} ]];
        then
                echo -e "\e[1;31mService must be specified as first argument\e[0m" >&2
                exit 1
        fi

        get_service_config

        echo -e "Distributing service \e[1;32m${service}\e[0m to \e[1;32m${_HST}\e[0m:\e[1;32m${_DST}\e[0m"

        if [[ -z ${_TGT} ]];
        then
                bin_path=target/release/${service}
        else
                bin_path=target/${_TGT}/release/${service}
        fi

        if [[ ! -f ${bin_path} ]];
        then
                echo -e "\e[1;31mBinary not found at ${bin_path}, please compile the service first\e[0m" >&2
                exit 1
        fi

        mkdir -p ${service}/dist
        cp -u ${bin_path} ${service}/dist/

        if [[ -f ${service}/${service}.service ]];
        then
                cp -u ${service}/${service}.service ${service}/dist/
        fi
        if [[ -f ${service}/${service}.yml ]];
        then
                cp -u ${service}/${service}.yml ${service}/dist/
        fi

        if [[ ${service} == "domotux" ]];
        then
                mkdir -p domotux/dist/facade
                cp -ru facade/dist/* domotux/dist/facade
        fi

        # upload to remote
        ssh ${_HST} "mkdir -p ${_DST}/${service}"
        rsync -va  ${service}/dist/ ${_HST}:${_DST}/${service}
}

service_install() {
        if [[ -z ${service} ]];
        then
                echo -e "\e[1;31mService must be specified as first argument\e[0m" >&2
                exit 1
        fi

        echo -e "Installing \e[1;32m${service}\e[0m service"

        get_service_config

        ssh ${_HST} 'bash -s' <<EOF
                cd ${_DST}/${service}
                if [[ ! -f ${service}.service || ! -f ${service} ]];
                then
                        echo -e "\e[1;31mService files not found in ${_DST}, please upload the service first\e[0m" >&2
                        exit 1
                fi

                # Create domotux user and group if not exists
                # id -u domotux &>/dev/null || sudo useradd -r -M -s /usr/sbin/nologin domotux

                # Install service binary and systemd unit file, and optionally config file
                sudo install ${service} /usr/local/bin/${service}
                sudo install ${service}.service /etc/systemd/system/${service}.service
                sudo systemctl daemon-reload
                if [[ -f ${service}.yml ]];
                then
                        sudo install ${service}.yml /etc/${service}.yml
                else
                        sudo rm -f /etc/${service}.yml
                fi

                # For domotux, also install frontend assets and set proper ownership and permissions
                if [[ ${service} == "domotux" ]];
                then
                        sudo rm -rf /usr/local/share/domotux

                        sudo install -d -o domotux -g domotux /usr/local/share/domotux/facade
                        sudo install -d -o domotux -g domotux /var/lib/domotux

                        sudo cp -ru facade/* /usr/local/share/domotux/facade/
                        sudo chown -R domotux:domotux /usr/local/share/domotux

                        sudo chown -R domotux:domotux /var/lib/domotux
                        sudo chmod -R 770 /var/lib/domotux
                fi
EOF
}

service_start() {
        if [[ -z ${service} ]];
        then
                echo -e "\e[1;31mService must be specified as first argument\e[0m" >&2
                exit 1
        fi

        echo -e "Starting \e[1;32m${service}\e[0m service"

        get_service_config

        ssh ${_HST} 'bash -s' <<EOF
                sudo systemctl start ${service}
                sudo systemctl enable ${service}
EOF
}

service_stop() {
        if [[ -z ${service} ]];
        then
                echo -e "\e[1;31mService must be specified as first argument\e[0m" >&2
                exit 1
        fi

        echo -e "Stopping \e[1;32m${service}\e[0m service"

        get_service_config

        ssh ${_HST} 'bash -s' <<EOF
                sudo systemctl stop ${service}
                sudo systemctl disable ${service}
EOF
}

service_restart() {
        if [[ -z ${service} ]];
        then
                echo -e "\e[1;31mService must be specified as first argument\e[0m" >&2
                exit 1
        fi

        echo -e "Restarting \e[1;32m${service}\e[0m service"

        get_service_config

        ssh ${_HST} 'bash -s' <<EOF
                cd ${_DST}
                if [[ ! -f ${service}.service || ! -f ${service} ]];
                then
                        echo -e "\e[1;31mService files not found in ${_DST}, please upload the service first\e[0m" >&2
                        exit 1
                fi

                sudo systemctl restart ${service}
EOF
}

service_status() {
        if [[ -z ${service} ]];
        then
                echo -e "\e[1;31mService must be specified as first argument\e[0m" >&2
                exit 1
        fi

        echo -e "Sleeping for 1 second to let journal catch up with service status changes"
        sleep 1

        echo -e "Checking status of \e[1;32m${service}\e[0m service"

        get_service_config

        ssh ${_HST} 'bash -s' <<EOF
                cd ${_DST}
                if [[ ! -f ${service}.service || ! -f ${service} ]];
                then
                        echo -e "\e[1;31mService files not found in ${_DST}, please upload the service first\e[0m" >&2
                        exit 1
                fi

                sudo systemctl status ${service}
EOF
}

prog=$0

service=
all_services=(linky wattflux tarifs-cre domotux)
service_specifiers=(all ${all_services[*]})

call_func() {
        local func=$1
        shift
        if [[ -z ${service} ]];
        then
                echo -e "\e[1;31mService must be specified as first argument\e[0m" >&2
                exit 1
        fi

        if [[ ${service} == "all" ]];
        then
                for s in ${all_services[*]};
                do
                        service=$s
                        ${func} "$@"
                done
        else
                ${func} "$@"
        fi
}

pushd ${DIR} > /dev/null

while [ $# -gt 0 ]
do
        case "$1" in
                ssh)
                        open_shell
                        ;;
                clean)
                        call_func service_clean
                        ;;
                compile)
                        call_func service_compile
                        ;;
                dist)
                        call_func service_dist
                        ;;
                install)
                        call_func service_install
                        ;;
                start)
                        call_func service_start
                        ;;
                stop)
                        call_func service_stop
                        ;;
                restart)
                        call_func service_restart
                        ;;
                status)
                        call_func service_status
                        ;;
                *)
                        if [[ " ${service_specifiers[*]} " =~ " ${1} " ]];
                        then
                                service=$1
                        else
                                echo -e "\e[1;31mUnknown service or command: $1\e[0m" >&2
                                echo "Usage: ${prog} [service] [command]" >&2
                                echo "Available services: ${service_specifiers[*]}"
                                echo "Available commands: ssh compile dist clean" >&2
                                exit 1
                        fi
                        ;;
        esac
        shift
done

popd > /dev/null
